import React, { createContext, useContext, useEffect, useState } from "react";
import { I18nManager, Platform } from "react-native";
import AsyncStorage from "@react-native-async-storage/async-storage";
import * as Updates from "expo-updates";
import { getLocales } from "expo-localization";

type Language = "en" | "ar";

const translations = {
  en: {
    // Tabs
    dashboard: "Dashboard", properties: "Properties", tenants: "Tenants",
    expenses: "Expenses", profile: "Profile",
    // Greetings
    goodMorning: "Good Morning", goodAfternoon: "Good Afternoon", goodEvening: "Good Evening",
    hereIsYourOverview: "Here is your portfolio overview",
    // Dashboard
    revenue: "Revenue", collected: "Collected", totalExpenses: "Expenses", netIncome: "Net Income",
    monthlyIncome: "Annual Expected Income", occupancyRate: "Occupancy Rate",
    recentUpdates: "Recent Updates", noUpdates: "No recent activity",
    pending: "Pending", thisMonth: "This Month", portfolio: "PORTFOLIO", collectedOf: "collected of",
    occupancyDetails: "Occupancy by Property", close: "Close",
    tenantBox: "Tenants", tapToSearch: "Tap to search",
    quickActions: "Quick Actions",
    // Properties
    noProperties: "No properties yet. Tap + to add your first.",
    addProperty: "Add Property", units: "units", occupied: "Occupied",
    propertyName: "Property Name", type: "Type", city: "City",
    totalUnits: "Total Units", floors: "Floors",
    villa: "Villa", apartment: "Apartment", commercial: "Building", shop: "Shop",
    riyadh: "Riyadh", alkharj: "Al-Kharj", jeddah: "Jeddah", dammam: "Dammam",
    property: "Property", add: "Add",
    // Units
    unit: "Unit", allUnits: "All Units", vacant: "Vacant", unitDetails: "Unit Details",
    addTenantToUnit: "Add Tenant to This Unit", noTenantYet: "No tenant assigned",
    tenantInfo: "Tenant Info", tenantName: "Tenant Name", rent: "Rent",
    collectPayment: "Collect Payment", paymentDate: "Payment Date",
    enterAmount: "Enter a valid amount", fillRequired: "Fill required fields",
    // Tenants
    addTenant: "Add Tenant", name: "Name", phone: "Phone Number",
    nationalId: "National ID", unitNumber: "Unit Number",
    monthlyRent: "Monthly Rent", leaseStart: "Lease Start", leaseEnd: "Lease End",
    active: "Active", expired: "Expired", all: "All", total: "Total",
    noTenants: "No tenants yet.", selectDate: "Select date",
    markAsPaid: "Collect", paymentAmount: "Amount Received (SAR)",
    paymentNotes: "Notes (optional)", recordPayment: "Record Payment",
    paymentHistory: "Payment History", noPayments: "No payments recorded",
    // Search
    searchTenants: "Search Tenants", searchPlaceholder: "Search by name, phone, unit...",
    noResults: "No results found",
    // Expenses
    addExpense: "Add Expense", water: "Water", electricity: "Electricity",
    maintenance: "Maintenance", cleaning: "Cleaning", other: "Other",
    amount: "Amount", date: "Date", description: "Description",
    totalThisMonth: "Total This Month", noExpenses: "No expenses yet. Tap + to add one.",
    category: "Category", suggestedCategory: "Suggested",
    // Profile
    appearance: "Appearance", darkMode: "Dark Mode", lightMode: "Light Mode",
    biometricLock: "Biometric Lock", biometricPrompt: "Unlock Amlakey", biometricFallback: "Use Password", biometricVerify: "Verify to enable", biometricRetry: "Try Again",
    language: "Language", about: "About", appVersion: "Version",
    profileTitle: "Amlakey", profileSubtitle: "Your Smart Property Manager",
    account: "Account", signOut: "Sign Out", signOutConfirm: "Are you sure you want to sign out?",
    // Auth screen
    authLogin: "Login", authSignUp: "Sign Up", authEmail: "Email", authPassword: "Password",
    authConfirmPassword: "Confirm Password", authForgotPassword: "Forgot Password?",
    authFullName: "Full Name", authFirstName: "First Name", authLastName: "Last Name", authPhone: "Phone Number",
    authEnterEmail: "Please enter your email first",
    authEnterBoth: "Please enter email and password", authInvalidEmail: "Please enter a valid email address",
    authNameRequired: "Please enter your name", authFirstNameRequired: "Please enter your first name", authLastNameRequired: "Please enter your last name",
    authPhoneInvalid: "Phone must be 05XXXXXXXX (10 digits)",
    authPasswordMismatch: "Passwords do not match", authPasswordMin: "Password must be at least 6 characters",
    authAccountCreated: "Account created! Check your email to confirm, then log in.",
    authResetSent: "Password reset link sent to your email",
    authPropertyMgmt: "Your Smart Property Manager",
    // Swipe actions / Edit modals
    edit: "Edit", delete: "Delete", notes: "Notes",
    previousTenants: "Previous Tenants",
    editLabel: "Edit Unit Name", labelHint: "Leave empty to use default",
    // Common
    save: "Save", cancel: "Cancel", done: "Done", sar: "SAR", error: "Error", payments: "Payments",
    failedToLoadData: "Failed to load data. Please try again.",
    nameRequired: "Name is required", amountRequired: "Amount is required",
    add2: "Add", perMonth: "/mo", perYear: "yr", unitsOccupied: "units occupied",
    back: "Back", monthlyIncome2: "Annual Expected Income (SAR)", floorCount: "No. of Floors",
    recentTenants: "Recent Tenants",
    // Recent updates page
    allUpdates: "All Updates", collections: "Collections",
    newTenant: "New Tenant", newExpense: "New Expense",
    // Expense editing
    editExpense: "Edit Expense",
    // Property enhancements
    otherCity: "Other",
    secAccount: "Electricity Account", nwcAccount: "Water Account",
    multipleSEC: "Multiple Accounts", multipleNWC: "Multiple Accounts",
    singleAccount: "Single Account",
    multipleAccountsHint: "You can add accounts per unit in unit settings",
    building: "Building",
    // Integration modal
    fetchBills: "Fetch Bills", fetchAll: "Fetch All",
    integrationAccounts: "Utility Accounts",
    noAccounts: "No utility accounts found. Add them in property settings.",
    fetchSuccess: "Bill fetched", fetchError: "Failed to fetch",
    billAdded: "Expense added", accountLabel: "Account",
    // Profile redesign
    quickStats: "Quick Stats", totalProperties: "Properties", totalTenants: "Tenants",
    monthlyRevenue: "Revenue", preferences: "Preferences",
    notifications: "Notifications", rentReminders: "Rent Reminders",
    leaseExpiryAlerts: "Lease Expiry Alerts", notificationSettings: "Notification Settings",
    security: "Security", changePassword: "Change Password",
    newPassword: "New Password", confirmPassword: "Confirm Password",
    passwordChanged: "Password updated successfully",
    passwordMismatch: "Passwords do not match", passwordTooShort: "Minimum 6 characters",
    helpSupport: "Help & Support", contactUs: "Contact Us",
    sendFeedback: "Send Feedback", rateApp: "Rate App",
    dataManagement: "Data", exportData: "Export Data",
    personalInfo: "Personal Info",
    // Tenant optional lease end
    addLeaseEnd: "Add lease end date", removeLeaseEnd: "Remove",
    openEndedLease: "Open-ended lease",
    // Bill sync
    syncAll: "Sync All", alreadySynced: "Synced", billUpdated: "Updated", billPaid: "Paid", billUnpaid: "Unpaid",
    // Overdue payments
    overduePayments: "Overdue Payments", tenantsOverdue: "tenants overdue",
    daysOverdue: "days overdue", overdue: "Overdue",
    // Performance page
    performance: "Performance", lastMonth: "Last Month",
    last3Months: "Last 3 Months", last6Months: "Last 6 Months",
    thisYear: "This Year", allTime: "All Time",
    allProperties: "All Properties", collectionRate: "Collection Rate",
    byCategory: "By Category", byProperty: "By Property",
    overdueCurrentOnly: "Overdue data is only available for the current month",
    noDataPeriod: "No data for this period",
    collectedVsExpenses: "Collected vs Expenses",
    recentPayments: "Recent Payments", recentExpensesList: "Recent Expenses",
    monthlyBreakdown: "Monthly Breakdown", expectedRevenue: "Expected Revenue",
    totalCollected: "Total Collected", totalExpensesLabel: "Total Expenses",
    netIncomeLabel: "Net Income",
    // Reports page
    reports: "Reports", exportAsPdf: "Export as PDF", exportAsSpreadsheet: "Export as Spreadsheet",
    generateReport: "Generate Report", reportGenerated: "Report generated successfully",
    revenueReport: "Revenue Report", expenseReport: "Expense Report",
    fullReport: "Full Report", selectReportType: "Select Report Type",
    // Personal info page
    accountInfo: "Account Info",
    // Ejar import
    importFromEjar: "Import from Ejar",
    ejarImport: "Ejar Import",
    tenantIdNumber: "Tenant ID Number",
    hijriBirthDate: "Hijri Birth Date",
    contractNumber: "Contract Number",
    fetchContract: "Fetch Contract",
    fetching: "Fetching...",
    contractDetails: "Contract Details",
    contractType: "Contract Type",
    contractStatus: "Contract Status",
    leaseStartDate: "Lease Start",
    leaseEndDate: "Lease End",
    annualRent: "Annual Rent",
    paymentFrequency: "Payment Frequency",
    tenant: "Tenant",
    landlord: "Landlord",
    district: "District",
    importData: "Import to App",
    contractNotFound: "Contract not found. Please check the details and try again.",
    ejarFetchError: "Failed to fetch contract data. Please try again.",
    monthly: "Monthly",
    quarterly: "Quarterly",
    semiAnnual: "Semi-Annual",
    annual: "Annual",
    paymentFrequencyMonthly: "Monthly",
    paymentFrequencySemiAnnual: "Semi-Annual",
    paymentFrequencyAnnual: "Annual",
    paymentFrequencyQuarterly: "Quarterly",
    contractImported: "Contract data imported successfully",
    enterTenantId: "Enter tenant national ID",
    enterHijriBirth: "YYYY/MM/DD",
    enterContractNo: "Enter Ejar contract number",
    residential: "Residential",
    // New keys for improvements
    forgotPassword: "Forgot password?",
    resetLinkSent: "Password reset link sent to your email",
    enterEmailFirst: "Please enter your email first",
    deleteBills: "Delete Bills",
    deleteBillsConfirm: "Delete all",
    bills: "bills",
    accountNumber: "Account Number",
    unitOptional: "Unit (Optional)",
    propertyRequired: "Property is required for utility bills",
    accountRequired: "Account number is required",
    fetchingBill: "Fetching bill...",
    today: "Today",
    yesterday: "Yesterday",
    thisWeek: "This Week",
    earlier: "Earlier",
    sortByName: "Name",
    sortByRent: "Rent",
    sortByDate: "Date",
    sortByAmount: "Amount",
    searchProperties: "Search properties...",
    selectAll: "Select All",
    deselectAll: "Deselect All",
    selectedTenants: "Selected Tenants",
    paymentRecorded: "Payment recorded",
    expenseAdded: "Expense added",
    expenseDeleted: "Expense deleted",
    propertyAdded: "Property added",
    propertyDeleted: "Property deleted",
    tenantAdded: "Tenant added",
    tenantDeleted: "Tenant deleted",
    saved: "Saved",
    noInternet: "No internet connection",
    offlineMode: "You're offline — data may be outdated",
    leaseExpiring: "Lease Expiring",
    leaseExpiringSoon: "leases expiring within 30 days",
    insurance: "Insurance",
    management: "Management",
    taxes: "Taxes",
    showAll: "Show All",
    stepLoadingForm: "Loading form...",
    stepSubmitting: "Submitting...",
    stepSearching: "Searching...",
    stepLoadingDetails: "Loading details...",
    duplicatePaymentWarning: "A payment for this period already exists. Record anyway?",
    proceed: "Proceed",
    swipeHint: "Swipe left for options",
    upToDate: "Up to date",
    needsSync: "Needs sync",
    paid: "Paid",
    syncError: "Sync error",
    // Share / Export
    shareReport: "Share Report",
    exportReport: "Export Report",
    performanceReport: "Property Performance Report",
    // Onboarding
    onboardingWelcome: "Welcome to Amlakey",
    onboardingWelcomeSub: "Your smart property management companion",
    onboardingPropertiesTitle: "Manage Properties",
    onboardingPropertiesDesc: "Add properties and units, track occupancy rates, and organize everything in one place",
    onboardingTenantsTitle: "Tenants & Payments",
    onboardingTenantsDesc: "Track tenants, collect rent, monitor overdue payments, and manage lease contracts",
    onboardingExpensesTitle: "Expenses & Reports",
    onboardingExpensesDesc: "Record expenses by category, view performance reports, and track your net income",
    onboardingSetupTitle: "Customize Your Experience",
    onboardingSetupTheme: "Choose Theme",
    onboardingSetupLang: "Choose Language",
    onboardingGetStarted: "Get Started",
    onboardingNext: "Next",
    onboardingBack: "Back",
    onboardingSkip: "Skip",
    // Validation
    required: "This field is required",
    validationPhoneInvalid: "Phone must be 10 digits starting with 05",
    validationRentTooHigh: "Maximum rent is 999,999 SAR",
    validationLeaseEndBeforeStart: "Lease end must be after lease start",
    validationAmountTooHigh: "Maximum amount is 999,999 SAR",
    validationAmountPositive: "Amount must be greater than zero",
    validationNameTooShort: "Name must be at least 4 characters",
    validationPropertyNameShort: "Name must be at least 2 characters",
    validationUnitsRequired: "Must be at least 1 unit",
    validationUnitsMax: "Maximum 500 units",
    validationFloorsMax: "Maximum 100 floors",
    validationDescriptionLong: "Maximum 200 characters",
    validationNationalId: "National ID must be 10 digits starting with 1 or 2",
    validationEmailInvalid: "Please enter a valid email address",
    validationPasswordShort: "Password must be at least 6 characters",
    validationPasswordMismatch: "Passwords do not match",
    validationFutureDateNotAllowed: "Date cannot be in the future",
    // Renew Lease
    renewLease: "Renew Lease",
    renewLeaseConfirm: "Set a new lease end date for this tenant.",
    newLeaseEnd: "New Lease End",
    renewing: "Renewing...",
    leaseRenewed: "Lease renewed successfully",
    // Notifications
    markAllRead: "Mark all read",
    noNotifications: "No notifications yet",
    clearAllNotifications: "Clear All",
    clearAllConfirm: "Clear all notifications?",
    rentDueTitle: "Rent Due Reminder",
    rentDueBody: "Rent for %name% is due in %days% days",
    overdueRentTitle: "Overdue Rent",
    overdueRentBody: "Rent from %name% is overdue (%amount% SAR)",
    overdueRentUrgentTitle: "Urgent: Overdue Rent",
    overdueRentUrgentBody: "Rent from %name% is %days% days overdue (%amount% SAR)",
    rentDueTodayTitle: "Rent Due Today",
    rentDueTodayBody: "%name%'s rent of %amount% SAR is due today",
    leaseExpiryTitle: "Lease Expiring Soon",
    leaseExpiryBody: "%name%'s lease expires in %days% days",
    paymentReceivedTitle: "Payment Received",
    paymentReceivedBody: "%amount% SAR received from %name%",
    rentDueReminders: "Rent Due Reminders",
    remindDaysBefore: "Remind before",
    overdueAlerts: "Overdue Rent Alerts",
    alertDaysBefore: "Alert before",
    paymentConfirmations: "Payment Confirmations",
    notificationSound: "Notification Sound",
    saveSettings: "Save Settings",
    daysLabel: "days",
    notifPermissionNeeded: "Enable notifications in your device settings to receive reminders",
    // WhatsApp / Reminders
    sendReminder: "Send Reminder",
    reminderMessage: "Dear %name%, this is a reminder that your rent of %amount% SAR is due. Please arrange payment at your earliest convenience. Thank you.",
    whatsappNotInstalled: "WhatsApp is not installed on this device",
    callTenant: "Call Tenant",
    // Notify
    broadcastMessage: "Notify",
    sendViaWhatsApp: "Send via WhatsApp",
    broadcastConfirm: "This will open WhatsApp for this tenant. Continue?",
    noPhoneNumber: "No phone",
    leaseRenewalMessage: "Dear %name%, your lease is expiring soon. Please contact us to discuss renewal. Thank you.",
    autoMessage: "Auto (based on status)",
    customMessage: "Custom Message",
    writeYourMessage: "Write your message here... Use %name% to insert tenant name.",
    messageType: "Message Type",
    filterAll: "All",
    filterOverdue: "Overdue",
    filterExpiring: "Expiring",
    tenantsSelected: "selected",
    markPaid: "Paid",
    markUnpaid: "Unpaid",
    // Receipt
    shareReceipt: "Share Receipt",
    receipt: "Receipt",
    receiptNumber: "Receipt No.",
    receiptThankYou: "Thank you for your payment",
    // Recurring Expenses
    repeatMonthly: "Repeat Monthly",
    recurringExpense: "Recurring",
    recurringAutoCreated: "Recurring expenses auto-created for this month",
    // Backup & Restore
    restoreData: "Restore Data",
    exportSuccess: "Data exported successfully",
    importSuccess: "Data restored successfully",
    importConfirm: "This will merge the backup data with your current data. Continue?",
    importWarning: "Restore Data",
    lastBackup: "Last backup",
    noBackupYet: "No backup yet",
    invalidBackupFile: "Invalid backup file format",
    backingUp: "Exporting...",
    restoring: "Restoring...",
    // Hijri Calendar
    hijriCalendar: "Hijri Calendar",
    leaseExpiryAlerts2: "Lease Expiry",
    // Delete property dialog
    deletePropertyTitle: "Delete Property",
    deletePropertyMsg: "This cannot be undone.",
    // Property detail
    tapToViewUnits: "Tap to view units",
    editProperty: "Edit Property",
    validDateFormat: "Enter a valid date (YYYY-MM-DD)",
    paymentsRecorded: "payments recorded successfully",
    tapOccupiedToSelect: "Tap occupied units to select",
    unitsSelected: "selected",
    unitsSelectedCount: "units selected",
    collectPaymentTitle: "Collect Payment",
    selectedUnitsLabel: "Selected Units",
    confirm: "Confirm",
    notesPlaceholder: "Notes...",
    // Auth
    enterYourName: "Enter your name", enterFirstName: "Enter first name", enterLastName: "Enter last name",
    noAccountSignUp: "Don't have an account? Sign up",
    hasAccountLogin: "Already have an account? Log in",
    // Reports (export)
    reportTitle: "Amlakey Report",
    sectionRevenue: "Revenue",
    sectionExpenses: "Expenses",
    sectionSummary: "Summary",
    revenueReportTitle: "Revenue Report",
    expensesReportTitle: "Expenses Report",
    reportSummaryTitle: "Report Summary",
    columnTenant: "Tenant",
    columnMonthlyRent: "Monthly Rent",
    columnProperty: "Property",
    columnDescription: "Description",
    columnAmount: "Amount",
    columnCategory: "Category",
    columnDate: "Date",
    columnRent: "Rent",
    activeTenants: "Active Tenants",
    reportFooter: "Amlakey — Your Smart Property Manager",
    // Profile
    footerText: "Amlakey - Your Smart Property Manager",
    addYourName: "Add your name",
    langChanged: "Language Changed",
    langChangedMsg: "Please restart the app to apply the full layout direction change.",
    ok: "OK",
    infoSaved: "Info saved successfully",
    database: "Database",
    connected: "Connected",
    // Personal Info
    emailLabel: "Email",
    fullNameLabel: "Full Name", firstNameLabel: "First Name", lastNameLabel: "Last Name",
    phoneLabel: "Phone",
    cityLabel: "City",
    companyLabel: "Company",
    companyPlaceholder: "Amlakey Real Estate",
    cityPlaceholder: "Riyadh",
    // Splash
    appName: "Amlakey",
    smartPropertyManager: "Your Smart Property Manager",
    // Unit detail
    endLease: "End Lease",
    frequency: "Frequency",
    holdToEdit: "Hold to edit",
    editPayment: "Edit Payment",
    enterManually: "Enter Manually",
    enterManuallyDesc: "Fill in tenant details yourself",
    fetchFromEjar: "Auto-fetch from Ejar contract",
    paymentFrequencyLabel: "Payment Frequency",
    exampleBankTransfer: "e.g. Bank transfer",
    // Dashboard / calendar
    leaseEndLabel: "Lease End",
    todayLabel: "Today",
    calSun: "Sun", calMon: "Mon", calTue: "Tue", calWed: "Wed", calThu: "Thu", calFri: "Fri", calSat: "Sat",
    // Calendar events
    calLeaseEnd: "Lease End",
    calRentDue: "Rent Due",
    calPaymentRecorded: "Payment Recorded",
    // Tenants
    noTenantsShort: "No tenants",
    leaseStartRequired: "Lease start date is required",
    leaseEndRequired: "Lease end date is required",
    syncing: "Syncing...",
    // Recent updates
    newTenantAdded: "New tenant added",
    rentCollected: "Rent collected",
    paymentReceived: "Payment received",
    tapToView: "Tap to view",
    // Tenant search
    expiresToday: "Expires today",
    expiresInDays: "Expires in %d% days",
    expiringSoon: "Expiring",
    deleteTenantMsg: "Remove \"%name%\" from the system? This cannot be undone.",
    // Ejar import
    loadingInquiryForm: "Loading inquiry form...",
    searching: "Searching...",
    loadingContractDetails: "Loading contract details...",
    loadingResults: "Loading results...",
    fillingForm: "Filling inquiry form...",
    hijriDob: "Date of Birth (Hijri)",
    exampleIdNumber: "Example: 1xxxxxxxxx",
    region: "Region",
    unpaidBills: "unpaid",
    pickerCancel: "Cancel",
    pickerDone: "Done",
    pickerDay: "Day",
    pickerMonth: "Month",
    pickerYear: "Year",
    // Expenses recurring
    recurringHintOn: "This expense will auto-repeat every month",
    recurringHintOff: "Tap to enable monthly repeat",
    // Terms & Privacy
    termsOfService: "Terms of Service",
    privacyPolicy: "Privacy Policy",
    bySigningUp: "By signing up, you agree to our",
    andWord: "and",
    lastUpdated: "Last Updated",
    // Terms sections
    termsIntroTitle: "Introduction",
    termsIntroBody: "Welcome to Amlakey. These Terms of Service govern your use of our property management application. By accessing or using Amlakey, you agree to be bound by these terms. If you do not agree, please do not use the application.",
    termsAccountTitle: "Account Responsibilities",
    termsAccountBody: "You are responsible for maintaining the confidentiality of your account credentials. You must provide accurate and complete information during registration. You agree to notify us immediately of any unauthorized access to your account. You must be at least 18 years old to create an account.",
    termsUsageTitle: "Acceptable Use",
    termsUsageBody: "You agree to use Amlakey only for lawful property management purposes. You shall not misuse the platform to store false tenant information, manipulate financial records, or engage in any fraudulent activity. You may not attempt to reverse-engineer, modify, or distribute any part of the application.",
    termsPaymentsTitle: "Payments & Financial Data",
    termsPaymentsBody: "Amlakey facilitates the recording and tracking of rental payments and expenses. All financial data entered is your responsibility to verify for accuracy. Amlakey is not a financial institution and does not process actual monetary transactions. We are not liable for any financial decisions made based on data within the application.",
    termsDataTitle: "Data & Privacy",
    termsDataBody: "Your use of Amlakey is also governed by our Privacy Policy. By using the application, you consent to the collection and use of your data as described in the Privacy Policy. You retain ownership of all property and tenant data you enter into the application.",
    termsTerminationTitle: "Termination",
    termsTerminationBody: "We reserve the right to suspend or terminate your account if you violate these terms. You may delete your account at any time through the application settings. Upon termination, your data may be retained for a reasonable period for backup and legal compliance purposes.",
    termsLiabilityTitle: "Limitation of Liability",
    termsLiabilityBody: "Amlakey is provided on an \"as is\" basis without warranties of any kind. We shall not be liable for any indirect, incidental, or consequential damages arising from your use of the application. Our total liability shall not exceed the amount paid by you for the service in the preceding 12 months.",
    termsChangesTitle: "Changes to Terms",
    termsChangesBody: "We may update these terms from time to time. We will notify you of significant changes through the application or via email. Continued use of Amlakey after changes constitutes acceptance of the updated terms.",
    termsContactTitle: "Contact Us",
    termsContactBody: "If you have questions about these Terms of Service, please contact us at support@amlakeyapp.com.",
    // Privacy sections
    privacyIntroTitle: "Introduction",
    privacyIntroBody: "At Amlakey, we take your privacy seriously. This Privacy Policy explains how we collect, use, store, and protect your personal information when you use our property management application.",
    privacyDataCollectedTitle: "Data We Collect",
    privacyDataCollectedBody: "We collect information you provide directly, including: your name, email address, and phone number during registration; property details such as names, addresses, and unit information; tenant information including names, contact details, and lease terms; financial records such as rental payments, expenses, and billing accounts; and device information for app functionality and security.",
    privacyHowWeUseTitle: "How We Use Your Data",
    privacyHowWeUseBody: "We use your data to: provide and maintain the property management service; send notifications about rent due dates and lease expirations; generate reports and performance analytics for your properties; facilitate data backup and restoration; and improve our application and user experience.",
    privacyDataStorageTitle: "Data Storage & Security",
    privacyDataStorageBody: "Your data is stored securely using industry-standard encryption. We use Supabase as our backend infrastructure with row-level security policies. Biometric authentication is available for additional app security. We regularly review and update our security practices to protect your information.",
    privacySharingTitle: "Third-Party Sharing",
    privacySharingBody: "We do not sell, trade, or rent your personal information to third parties. We may share data only with: service providers necessary for app operation (hosting, authentication); legal authorities when required by law or court order; and with your explicit consent for any other purpose.",
    privacyRightsTitle: "Your Rights",
    privacyRightsBody: "You have the right to: access and view all your personal data stored in the application; export your data at any time through the app settings; request correction of inaccurate information; request deletion of your account and associated data; and withdraw consent for data processing at any time.",
    privacyChangesTitle: "Changes to This Policy",
    privacyChangesBody: "We may update this Privacy Policy periodically. We will notify you of material changes through the application. The \"Last Updated\" date at the top of this page indicates when the policy was last revised.",
    privacyContactTitle: "Contact Us",
    privacyContactBody: "For privacy-related inquiries, please contact us at support@amlakeyapp.com.",
    // Subscription
    subscriptionTitle: "Upgrade to Pro",
    currentPlan: "Current Plan",
    freePlan: "Free",
    proPlan: "Pro",
    proMonthly: "Monthly",
    proAnnual: "Annual",
    proPriceMonth: "/month",
    proPriceYear: "/year",
    savePercent: "Save 50%",
    subscribePro: "Subscribe to Pro",
    restorePurchases: "Restore Purchases",
    restoreSuccess: "Purchases restored successfully!",
    restoreNone: "No previous purchases found.",
    subscriptionActive: "Pro subscription active",
    subscriptionManage: "Manage Subscription",
    upgradeRequired: "Upgrade Required",
    upgradeToUnlock: "Upgrade to Pro to unlock this feature",
    propertyLimitTitle: "Property Limit Reached",
    propertyLimitMsg: "Free plan allows up to 3 properties. Upgrade to Pro for unlimited properties.",
    unitLimitTitle: "Unit Limit Reached",
    unitLimitMsg: "Free plan allows up to 5 units per property. Upgrade to Pro for unlimited units.",
    upgrade: "Upgrade",
    later: "Later",
    proFeatures: "Pro Features",
    featureUnlimitedProperties: "Unlimited Properties",
    featureUnlimitedUnits: "Unlimited Units",
    featureWhatsAppBroadcast: "WhatsApp Broadcast",
    featureExportReports: "Export Reports",
    featureDarkMode: "Dark Mode",
    featureUnlimitedPropertiesDesc: "Add unlimited properties to manage your portfolio",
    featureUnlimitedUnitsDesc: "No limit on units per property",
    featureWhatsAppBroadcastDesc: "Send bulk messages to tenants via WhatsApp",
    featureExportReportsDesc: "Export and share performance reports",
    featureDarkModeDesc: "Easy on the eyes with dark mode",
    featureVault: "Document Vault",
    featureVaultDesc: "Securely store property deeds, contracts, and important documents",
    vault: "Vault",
    vaultTitle: "Document Vault",
    addDocument: "Upload Document",
    documentName: "Document Name",
    documentType: "Document Type",
    selectProperty: "Select Property",
    expiryDate: "Expiry Date",
    noDocuments: "No documents yet",
    noDocumentsDesc: "Tap + to upload your first document.",
    uploadSuccess: "Document uploaded successfully",
    deleteDocument: "Delete Document",
    deleteDocumentConfirm: "Are you sure you want to delete this document?",
    viewDocument: "View Document",
    downloadDocument: "Download",
    documents: "Documents",
    docTypeDeed: "Property Deed",
    docTypePermit: "Building Permit",
    docTypeContract: "Lease Contract",
    docTypeInsurance: "Insurance Policy",
    docTypeMaintenance: "Maintenance Record",
    docTypeTax: "Tax Document",
    docTypeOther: "Other",
    allDocuments: "All",
    documentExpiring: "Expiring Soon",
    documentExpired: "Expired",
    uploading: "Uploading...",
    freeIncludes: "Free Plan Includes",
    freeProperties: "Up to 3 properties",
    freeUnits: "Up to 5 units per property",
    freePaymentTracking: "Payment tracking",
    freeNotifications: "Notifications",
    freeEjarImport: "Ejar import",
    cancelAnytime: "Cancel anytime. Subscriptions auto-renew.",
    // Landing page
    landingLogin: "Log In",
    landingGetStarted: "Get Started",
    landingDownload: "Download on App Store",
    landingUseWeb: "Use Web App",
    landingHeroTag: "Property Management Made Simple",
    landingHeroTitle1: "Manage Your Properties",
    landingHeroTitle2: "Like a Pro",
    landingHeroDesc: "The all-in-one platform built for Saudi landlords. Track properties, tenants, payments, and expenses from your phone or browser.",
    landingTrustedBy: "Trusted by landlords across Saudi Arabia",
    landingFeaturesTitle: "Everything You Need to Manage Properties",
    landingFeaturesSub: "Built for Saudi landlords who want simplicity and control",
    landingFeat1Title: "Property Portfolio",
    landingFeat1Desc: "Manage apartments, villas, commercial buildings, and land parcels all in one place.",
    landingFeat2Title: "Tenant Management",
    landingFeat2Desc: "Track tenant details, lease dates, and contact information with ease.",
    landingFeat3Title: "Payment Tracking",
    landingFeat3Desc: "Record rent payments, track overdue amounts, and never miss a collection.",
    landingFeat4Title: "Performance Reports",
    landingFeat4Desc: "See collection rates, revenue breakdowns, and financial performance at a glance.",
    landingFeat5Title: "WhatsApp Notifications",
    landingFeat5Desc: "Send payment reminders and lease renewal messages to tenants directly via WhatsApp.",
    landingFeat6Title: "Smart Alerts",
    landingFeat6Desc: "Get push notifications for overdue payments, expiring leases, and important reminders.",
    landingFeat7Title: "Expense Tracking",
    landingFeat7Desc: "Log maintenance costs, utility bills, and all property expenses in one place.",
    landingFeat8Title: "Dashboard Analytics",
    landingFeat8Desc: "Real-time overview of revenue, collection rates, net income, and occupancy.",
    landingFeat9Title: "Bilingual Support",
    landingFeat9Desc: "Full Arabic and English interface with complete RTL support. Switch anytime.",
    landingFeat10Title: "Dark Mode",
    landingFeat10Desc: "Easy on the eyes. Switch between light and dark themes with one tap.",
    landingFeat11Title: "Cross-Platform",
    landingFeat11Desc: "Works on iPhone and web browser. Your data syncs everywhere.",
    landingFeat12Title: "Export Reports",
    landingFeat12Desc: "Generate PDF and Excel reports for payments, expenses, and property performance.",
    landingStatsProperties: "Properties Managed",
    landingStatsTransactions: "Transactions Tracked",
    landingStatsUptime: "Uptime",
    landingStatsPlatforms: "Platforms",
    landingHowTitle: "How It Works",
    landingHowSub: "Get started in minutes, not hours",
    landingHow1Title: "Create Your Account",
    landingHow1Desc: "Sign up for free in seconds with just your email.",
    landingHow2Title: "Add Your Properties",
    landingHow2Desc: "Enter your properties and units. Import from Ejar if you prefer.",
    landingHow3Title: "Manage Everything",
    landingHow3Desc: "Track tenants, collect rent, monitor expenses, and grow your portfolio.",
    landingCtaTitle: "Ready to Simplify Your Property Management?",
    landingCtaSub: "Join landlords across Saudi Arabia who trust Amlakey.",
    landingPricingTitle: "Simple Price with Huge Capabilities",
    landingPricingSub: "Start free, upgrade when you need more",
    landingFree: "Free",
    landingPro: "Pro",
    landingBestValue: "BEST VALUE",
    landingOrYearly: "or 89 SAR/year (save 50%)",
    landingPriceFreeItems: "Up to 3 properties|5 units per property|Payment tracking|Notifications|WhatsApp messages|Dark mode",
    landingPriceFreeDisabled: "Export reports|Document Vault",
    landingPriceProItems: "Unlimited properties|Unlimited units|Payment tracking|Notifications|WhatsApp messages|Export reports (PDF & Excel)|Document Vault",
    landingBilingualTitle: "Fully Bilingual",
    landingBilingualSub: "Switch between English and Arabic with full RTL support",
    landingFooterBrand: "Amlakey | أملاكي",
    landingFooterSub: "Your Smart Property Manager",
    landingFooterContact: "Contact Us",
    landingCopyright: "© 2026 Amlakey. All rights reserved.",
  },
  ar: {
    // Tabs
    dashboard: "الرئيسية", properties: "العقارات", tenants: "المستأجرين",
    expenses: "المصاريف", profile: "الملف",
    // Greetings
    goodMorning: "صباح الخير", goodAfternoon: "مساء الخير", goodEvening: "مساء النور",
    hereIsYourOverview: "إليك نظرة عامة على محفظتك",
    // Dashboard
    revenue: "الإيجارات المتوقعة", collected: "المحصّل", totalExpenses: "المصاريف", netIncome: "صافي الدخل",
    monthlyIncome: "الدخل السنوي المتوقع", occupancyRate: "نسبة الإشغال",
    recentUpdates: "آخر التحديثات", noUpdates: "لا يوجد نشاط حديث",
    pending: "قيد الانتظار", thisMonth: "هذا الشهر", portfolio: "محفظتي", collectedOf: "محصّل من",
    occupancyDetails: "الإشغال حسب العقار", close: "إغلاق",
    tenantBox: "المستأجرون", tapToSearch: "اضغط للبحث",
    quickActions: "إجراءات سريعة",
    // Properties
    noProperties: "لا توجد عقارات. اضغط + للإضافة.",
    addProperty: "إضافة عقار", units: "وحدة", occupied: "مؤجرة",
    propertyName: "اسم العقار", type: "النوع", city: "المدينة",
    totalUnits: "عدد الوحدات", floors: "أدوار",
    villa: "فيلا", apartment: "شقق", commercial: "مبنى", shop: "محل",
    riyadh: "الرياض", alkharj: "الخرج", jeddah: "جدة", dammam: "الدمام",
    property: "العقار", add: "إضافة",
    // Units
    unit: "وحدة", allUnits: "كل الوحدات", vacant: "شاغرة", unitDetails: "تفاصيل الوحدة",
    addTenantToUnit: "إضافة مستأجر لهذه الوحدة", noTenantYet: "لا يوجد مستأجر",
    tenantInfo: "بيانات المستأجر", tenantName: "اسم المستأجر", rent: "الإيجار",
    collectPayment: "تحصيل الإيجار", paymentDate: "تاريخ الدفع",
    enterAmount: "أدخل مبلغاً صحيحاً", fillRequired: "أكمل الحقول المطلوبة",
    // Tenants
    addTenant: "إضافة مستأجر", name: "الاسم", phone: "رقم الجوال",
    nationalId: "رقم الهوية", unitNumber: "رقم الوحدة",
    monthlyRent: "الإيجار الشهري", leaseStart: "بداية العقد", leaseEnd: "نهاية العقد",
    active: "نشط", expired: "منتهي", all: "الكل", total: "الإجمالي",
    noTenants: "لا يوجد مستأجرون.", selectDate: "اختر تاريخ",
    markAsPaid: "تحصيل", paymentAmount: "المبلغ المحصّل (ريال)",
    paymentNotes: "ملاحظات (اختياري)", recordPayment: "تسجيل الدفعة",
    paymentHistory: "سجل المدفوعات", noPayments: "لا توجد مدفوعات مسجلة",
    // Search
    searchTenants: "بحث عن مستأجر", searchPlaceholder: "البحث بالاسم، الجوال، الوحدة...",
    noResults: "لا توجد نتائج",
    // Expenses
    addExpense: "إضافة مصروف", water: "ماء", electricity: "كهرباء",
    maintenance: "صيانة", cleaning: "نظافة", other: "أخرى",
    amount: "المبلغ", date: "التاريخ", description: "الوصف",
    totalThisMonth: "إجمالي هذا الشهر", noExpenses: "لا توجد مصاريف. اضغط + للإضافة.",
    category: "الفئة", suggestedCategory: "مقترح",
    // Profile
    appearance: "المظهر", darkMode: "الوضع الداكن", lightMode: "الوضع الفاتح",
    biometricLock: "القفل البيومتري", biometricPrompt: "فتح أملاكي", biometricFallback: "استخدم كلمة المرور", biometricVerify: "تحقق للتفعيل", biometricRetry: "حاول مرة أخرى",
    language: "اللغة", about: "عن التطبيق", appVersion: "الإصدار",
    profileTitle: "أملاكي", profileSubtitle: "مدير عقاراتك الذكي",
    account: "الحساب", signOut: "تسجيل الخروج", signOutConfirm: "هل أنت متأكد من تسجيل الخروج؟",
    // Auth screen
    authLogin: "تسجيل الدخول", authSignUp: "إنشاء حساب", authEmail: "البريد الإلكتروني", authPassword: "كلمة المرور",
    authConfirmPassword: "تأكيد كلمة المرور", authForgotPassword: "نسيت كلمة المرور؟",
    authFullName: "الاسم الكامل", authFirstName: "الاسم الأول", authLastName: "اسم العائلة", authPhone: "رقم الجوال",
    authEnterEmail: "الرجاء إدخال بريدك الإلكتروني أولاً",
    authEnterBoth: "الرجاء إدخال البريد الإلكتروني وكلمة المرور", authInvalidEmail: "الرجاء إدخال بريد إلكتروني صحيح",
    authNameRequired: "الرجاء إدخال اسمك", authFirstNameRequired: "الرجاء إدخال الاسم الأول", authLastNameRequired: "الرجاء إدخال اسم العائلة",
    authPhoneInvalid: "رقم الجوال يجب أن يبدأ بـ 05 ويتكون من 10 أرقام",
    authPasswordMismatch: "كلمات المرور غير متطابقة", authPasswordMin: "كلمة المرور يجب أن تكون 6 أحرف على الأقل",
    authAccountCreated: "تم إنشاء الحساب! تحقق من بريدك الإلكتروني للتأكيد، ثم سجّل الدخول.",
    authResetSent: "تم إرسال رابط إعادة تعيين كلمة المرور إلى بريدك الإلكتروني",
    authPropertyMgmt: "مدير عقاراتك الذكي",
    // Swipe actions / Edit modals
    edit: "تعديل", delete: "حذف", notes: "ملاحظات",
    previousTenants: "المستأجرون السابقون",
    editLabel: "تعديل اسم الوحدة", labelHint: "اتركه فارغاً للاستخدام الافتراضي",
    // Common
    save: "حفظ", cancel: "إلغاء", done: "تم", sar: "ريال", error: "خطأ", payments: "مدفوعات",
    failedToLoadData: "فشل تحميل البيانات. يرجى المحاولة مرة أخرى.",
    nameRequired: "الاسم مطلوب", amountRequired: "المبلغ مطلوب",
    add2: "إضافة", perMonth: "/شهر", perYear: "سنة", unitsOccupied: "وحدة مؤجرة",
    back: "رجوع", monthlyIncome2: "الدخل السنوي المتوقع (ريال)", floorCount: "عدد الأدوار",
    recentTenants: "آخر المستأجرين",
    // Recent updates page
    allUpdates: "كل التحديثات", collections: "التحصيلات",
    newTenant: "مستأجر جديد", newExpense: "مصروف جديد",
    // Expense editing
    editExpense: "تعديل المصروف",
    // Property enhancements
    otherCity: "أخرى",
    secAccount: "حساب الكهرباء", nwcAccount: "حساب المياه",
    multipleSEC: "حسابات متعددة", multipleNWC: "حسابات متعددة",
    singleAccount: "حساب واحد",
    multipleAccountsHint: "يمكنك إضافة الحسابات لكل وحدة في إعدادات الوحدة",
    building: "مبنى",
    // Integration modal
    fetchBills: "جلب الفواتير", fetchAll: "جلب الكل",
    integrationAccounts: "حسابات الخدمات",
    noAccounts: "لا توجد حسابات خدمات. أضفها في إعدادات العقار.",
    fetchSuccess: "تم جلب الفاتورة", fetchError: "فشل الجلب",
    billAdded: "تمت إضافة المصروف", accountLabel: "حساب",
    // Profile redesign
    quickStats: "إحصائيات سريعة", totalProperties: "العقارات", totalTenants: "المستأجرون",
    monthlyRevenue: "الإيرادات", preferences: "التفضيلات",
    notifications: "الإشعارات", rentReminders: "تذكيرات الإيجار",
    leaseExpiryAlerts: "تنبيهات انتهاء العقد", notificationSettings: "إعدادات الإشعارات",
    security: "الأمان", changePassword: "تغيير كلمة المرور",
    newPassword: "كلمة المرور الجديدة", confirmPassword: "تأكيد كلمة المرور",
    passwordChanged: "تم تحديث كلمة المرور بنجاح",
    passwordMismatch: "كلمات المرور غير متطابقة", passwordTooShort: "٦ أحرف على الأقل",
    helpSupport: "المساعدة والدعم", contactUs: "تواصل معنا",
    sendFeedback: "إرسال ملاحظات", rateApp: "تقييم التطبيق",
    dataManagement: "البيانات", exportData: "تصدير البيانات",
    personalInfo: "المعلومات الشخصية",
    // Tenant optional lease end
    addLeaseEnd: "إضافة تاريخ انتهاء العقد", removeLeaseEnd: "إزالة",
    openEndedLease: "عقد مفتوح المدة",
    // Bill sync
    syncAll: "مزامنة الكل", alreadySynced: "تمت المزامنة", billUpdated: "تم التحديث", billPaid: "مدفوعة", billUnpaid: "غير مدفوعة",
    // Overdue payments
    overduePayments: "مدفوعات متأخرة", tenantsOverdue: "مستأجر متأخر",
    daysOverdue: "يوم متأخر", overdue: "متأخر",
    // Performance page
    performance: "الأداء", lastMonth: "الشهر الماضي",
    last3Months: "آخر 3 أشهر", last6Months: "آخر 6 أشهر",
    thisYear: "هذه السنة", allTime: "كل الفترة",
    allProperties: "جميع العقارات", collectionRate: "نسبة التحصيل",
    byCategory: "حسب الفئة", byProperty: "حسب العقار",
    overdueCurrentOnly: "بيانات المتأخرات متاحة للشهر الحالي فقط",
    noDataPeriod: "لا توجد بيانات لهذه الفترة",
    collectedVsExpenses: "المحصّل مقابل المصاريف",
    recentPayments: "آخر المدفوعات", recentExpensesList: "آخر المصاريف",
    monthlyBreakdown: "تفصيل شهري", expectedRevenue: "الإيرادات المتوقعة",
    totalCollected: "إجمالي المحصّل", totalExpensesLabel: "إجمالي المصاريف",
    netIncomeLabel: "صافي الدخل",
    // Reports page
    reports: "التقارير", exportAsPdf: "تصدير كـ PDF", exportAsSpreadsheet: "تصدير كجدول بيانات",
    generateReport: "إنشاء تقرير", reportGenerated: "تم إنشاء التقرير بنجاح",
    revenueReport: "تقرير الإيرادات", expenseReport: "تقرير المصاريف",
    fullReport: "تقرير شامل", selectReportType: "اختر نوع التقرير",
    // Personal info page
    accountInfo: "معلومات الحساب",
    // Ejar import
    importFromEjar: "استيراد من إيجار",
    ejarImport: "استيراد إيجار",
    tenantIdNumber: "رقم هوية المستأجر",
    hijriBirthDate: "تاريخ الميلاد هجري",
    contractNumber: "رقم العقد",
    fetchContract: "جلب العقد",
    fetching: "جاري الجلب...",
    contractDetails: "تفاصيل العقد",
    contractType: "نوع العقد",
    contractStatus: "حالة العقد",
    leaseStartDate: "بداية العقد",
    leaseEndDate: "نهاية العقد",
    annualRent: "الإيجار السنوي",
    paymentFrequency: "دورة الدفع",
    tenant: "المستأجر",
    landlord: "المؤجر",
    district: "الحي",
    importData: "استيراد للتطبيق",
    contractNotFound: "لم يتم العثور على العقد. يرجى التحقق من البيانات والمحاولة مرة أخرى.",
    ejarFetchError: "فشل في جلب بيانات العقد. يرجى المحاولة مرة أخرى.",
    monthly: "شهري",
    quarterly: "ربع سنوي",
    semiAnnual: "نصف سنوي",
    annual: "سنوي",
    paymentFrequencyMonthly: "شهري",
    paymentFrequencySemiAnnual: "نصف سنوي",
    paymentFrequencyAnnual: "سنوي",
    paymentFrequencyQuarterly: "ربع سنوي",
    contractImported: "تم استيراد بيانات العقد بنجاح",
    enterTenantId: "أدخل رقم هوية المستأجر",
    enterHijriBirth: "سنة/شهر/يوم",
    enterContractNo: "أدخل رقم عقد إيجار",
    residential: "سكني",
    // New keys for improvements
    forgotPassword: "نسيت كلمة المرور؟",
    resetLinkSent: "تم إرسال رابط إعادة تعيين كلمة المرور",
    enterEmailFirst: "يرجى إدخال بريدك الإلكتروني أولاً",
    deleteBills: "حذف الفواتير",
    deleteBillsConfirm: "حذف جميع",
    bills: "الفواتير",
    accountNumber: "رقم الحساب",
    unitOptional: "الوحدة (اختياري)",
    propertyRequired: "العقار مطلوب لفواتير الخدمات",
    accountRequired: "رقم الحساب مطلوب",
    fetchingBill: "جاري جلب الفاتورة...",
    today: "اليوم",
    yesterday: "أمس",
    thisWeek: "هذا الأسبوع",
    earlier: "سابقاً",
    sortByName: "الاسم",
    sortByRent: "الإيجار",
    sortByDate: "التاريخ",
    sortByAmount: "المبلغ",
    searchProperties: "ابحث عن عقار...",
    selectAll: "تحديد الكل",
    deselectAll: "إلغاء التحديد",
    selectedTenants: "المستأجرون المحددون",
    paymentRecorded: "تم تسجيل الدفعة",
    expenseAdded: "تمت إضافة المصروف",
    expenseDeleted: "تم حذف المصروف",
    propertyAdded: "تمت إضافة العقار",
    propertyDeleted: "تم حذف العقار",
    tenantAdded: "تمت إضافة المستأجر",
    tenantDeleted: "تم حذف المستأجر",
    saved: "تم الحفظ",
    noInternet: "لا يوجد اتصال بالإنترنت",
    offlineMode: "أنت غير متصل — قد تكون البيانات قديمة",
    leaseExpiring: "العقد ينتهي قريباً",
    leaseExpiringSoon: "عقود تنتهي خلال 30 يوم",
    insurance: "تأمين",
    management: "إدارة",
    taxes: "ضرائب",
    showAll: "عرض الكل",
    stepLoadingForm: "تحميل النموذج...",
    stepSubmitting: "جاري الإرسال...",
    stepSearching: "جاري البحث...",
    stepLoadingDetails: "جاري تحميل التفاصيل...",
    duplicatePaymentWarning: "يوجد دفعة مسجلة لهذه الفترة. هل تريد التسجيل؟",
    proceed: "متابعة",
    swipeHint: "اسحب لليسار للخيارات",
    upToDate: "محدّث",
    needsSync: "يحتاج مزامنة",
    paid: "مدفوعة",
    syncError: "خطأ مزامنة",
    // Share / Export
    shareReport: "مشاركة التقرير",
    exportReport: "تصدير التقرير",
    performanceReport: "تقرير أداء العقارات",
    // Onboarding
    onboardingWelcome: "أهلاً بك في أملاكي",
    onboardingWelcomeSub: "رفيقك الذكي في إدارة العقارات",
    onboardingPropertiesTitle: "إدارة العقارات",
    onboardingPropertiesDesc: "أضف عقاراتك ووحداتك، وتابع نسب الإشغال، ونظم كل شيء في مكان واحد",
    onboardingTenantsTitle: "المستأجرون والمدفوعات",
    onboardingTenantsDesc: "تابع المستأجرين، حصّل الإيجارات، راقب المتأخرات، وأدر عقود الإيجار",
    onboardingExpensesTitle: "المصاريف والتقارير",
    onboardingExpensesDesc: "سجّل المصاريف حسب الفئة، واستعرض تقارير الأداء، وتابع صافي دخلك",
    onboardingSetupTitle: "خصّص تجربتك",
    onboardingSetupTheme: "اختر المظهر",
    onboardingSetupLang: "اختر اللغة",
    onboardingGetStarted: "ابدأ الآن",
    onboardingNext: "التالي",
    onboardingBack: "رجوع",
    onboardingSkip: "تخطي",
    // Validation
    required: "هذا الحقل مطلوب",
    validationPhoneInvalid: "رقم الجوال يجب أن يكون 10 أرقام ويبدأ بـ 05",
    validationRentTooHigh: "الحد الأقصى للإيجار 999,999 ريال",
    validationLeaseEndBeforeStart: "نهاية العقد يجب أن تكون بعد بداية العقد",
    validationAmountTooHigh: "الحد الأقصى للمبلغ 999,999 ريال",
    validationAmountPositive: "المبلغ يجب أن يكون أكبر من صفر",
    validationNameTooShort: "الاسم يجب أن يكون 4 أحرف على الأقل",
    validationPropertyNameShort: "الاسم يجب أن يكون حرفين على الأقل",
    validationUnitsRequired: "يجب أن يكون وحدة واحدة على الأقل",
    validationUnitsMax: "الحد الأقصى 500 وحدة",
    validationFloorsMax: "الحد الأقصى 100 طابق",
    validationDescriptionLong: "الحد الأقصى 200 حرف",
    validationNationalId: "رقم الهوية يجب أن يكون 10 أرقام ويبدأ بـ 1 أو 2",
    validationEmailInvalid: "يرجى إدخال بريد إلكتروني صحيح",
    validationPasswordShort: "كلمة المرور يجب أن تكون 6 أحرف على الأقل",
    validationPasswordMismatch: "كلمات المرور غير متطابقة",
    validationFutureDateNotAllowed: "لا يمكن اختيار تاريخ مستقبلي",
    // Renew Lease
    renewLease: "تجديد العقد",
    renewLeaseConfirm: "حدد تاريخ انتهاء العقد الجديد لهذا المستأجر.",
    newLeaseEnd: "نهاية العقد الجديدة",
    renewing: "جاري التجديد...",
    leaseRenewed: "تم تجديد العقد بنجاح",
    // Notifications
    markAllRead: "تحديد الكل كمقروء",
    noNotifications: "لا توجد إشعارات بعد",
    clearAllNotifications: "مسح الكل",
    clearAllConfirm: "مسح جميع الإشعارات؟",
    rentDueTitle: "تذكير بموعد الإيجار",
    rentDueBody: "إيجار %name% مستحق خلال %days% أيام",
    overdueRentTitle: "إيجار متأخر",
    overdueRentBody: "إيجار %name% متأخر (%amount% ريال)",
    overdueRentUrgentTitle: "عاجل: إيجار متأخر",
    overdueRentUrgentBody: "إيجار %name% متأخر بـ %days% أيام (%amount% ريال)",
    rentDueTodayTitle: "الإيجار مستحق اليوم",
    rentDueTodayBody: "إيجار %name% بقيمة %amount% ريال مستحق اليوم",
    leaseExpiryTitle: "انتهاء عقد قريب",
    leaseExpiryBody: "عقد %name% ينتهي خلال %days% يوم",
    paymentReceivedTitle: "تم استلام دفعة",
    paymentReceivedBody: "تم استلام %amount% ريال من %name%",
    rentDueReminders: "تذكيرات موعد الإيجار",
    remindDaysBefore: "تذكير قبل",
    overdueAlerts: "تنبيهات الإيجار المتأخر",
    alertDaysBefore: "تنبيه قبل",
    paymentConfirmations: "تأكيدات الدفع",
    notificationSound: "صوت الإشعارات",
    saveSettings: "حفظ الإعدادات",
    daysLabel: "أيام",
    notifPermissionNeeded: "فعّل الإشعارات في إعدادات جهازك لتلقي التذكيرات",
    // WhatsApp / Reminders
    sendReminder: "إرسال تذكير",
    reminderMessage: "عزيزي %name%، نذكركم بأن الإيجار المستحق بمبلغ %amount% ريال قد حان موعد سداده. نرجو ترتيب الدفع في أقرب وقت. شكراً لكم.",
    whatsappNotInstalled: "تطبيق واتساب غير مثبت على الجهاز",
    callTenant: "اتصال بالمستأجر",
    // Notify
    broadcastMessage: "إشعار",
    sendViaWhatsApp: "إرسال عبر واتساب",
    broadcastConfirm: "سيتم فتح واتساب لهذا المستأجر. هل تريد المتابعة؟",
    noPhoneNumber: "لا يوجد رقم",
    leaseRenewalMessage: "عزيزي %name%، عقد الإيجار الخاص بكم على وشك الانتهاء. نرجو التواصل معنا لمناقشة التجديد. شكراً لكم.",
    autoMessage: "تلقائي (حسب الحالة)",
    customMessage: "رسالة مخصصة",
    writeYourMessage: "اكتب رسالتك هنا... استخدم %name% لإدراج اسم المستأجر.",
    messageType: "نوع الرسالة",
    filterAll: "الكل",
    filterOverdue: "متأخرون",
    filterExpiring: "عقود منتهية",
    tenantsSelected: "مختار",
    markPaid: "مدفوع",
    markUnpaid: "غير مدفوع",
    // Receipt
    shareReceipt: "مشاركة الإيصال",
    receipt: "إيصال",
    receiptNumber: "رقم الإيصال",
    receiptThankYou: "شكراً لسداد الدفعة",
    // Recurring Expenses
    repeatMonthly: "تكرار شهري",
    recurringExpense: "متكرر",
    recurringAutoCreated: "تم إنشاء المصاريف المتكررة لهذا الشهر تلقائياً",
    // Backup & Restore
    restoreData: "استعادة البيانات",
    exportSuccess: "تم تصدير البيانات بنجاح",
    importSuccess: "تم استعادة البيانات بنجاح",
    importConfirm: "سيتم دمج بيانات النسخة الاحتياطية مع بياناتك الحالية. هل تريد المتابعة؟",
    importWarning: "استعادة البيانات",
    lastBackup: "آخر نسخة احتياطية",
    noBackupYet: "لا توجد نسخة احتياطية",
    invalidBackupFile: "صيغة ملف النسخة الاحتياطية غير صالحة",
    backingUp: "جاري التصدير...",
    restoring: "جاري الاستعادة...",
    // Hijri Calendar
    hijriCalendar: "التقويم الهجري",
    leaseExpiryAlerts2: "انتهاء العقد",
    // Delete property dialog
    deletePropertyTitle: "حذف العقار",
    deletePropertyMsg: "لا يمكن التراجع عن هذا الإجراء.",
    // Property detail
    tapToViewUnits: "اضغط لعرض الوحدات",
    editProperty: "تعديل العقار",
    validDateFormat: "أدخل تاريخاً صحيحاً",
    paymentsRecorded: "تم تسجيل الدفعات بنجاح",
    tapOccupiedToSelect: "اضغط على الوحدات المشغولة لتحديدها",
    unitsSelected: "محددة",
    unitsSelectedCount: "وحدات محددة",
    collectPaymentTitle: "تحصيل الإيجار",
    selectedUnitsLabel: "الوحدات المحددة",
    confirm: "تأكيد",
    notesPlaceholder: "ملاحظات...",
    // Auth
    enterYourName: "أدخل اسمك", enterFirstName: "أدخل الاسم الأول", enterLastName: "أدخل اسم العائلة",
    noAccountSignUp: "ليس لديك حساب؟ أنشئ حساب",
    hasAccountLogin: "لديك حساب؟ سجّل الدخول",
    // Reports (export)
    reportTitle: "تقرير أملاكي",
    sectionRevenue: "الإيرادات",
    sectionExpenses: "المصاريف",
    sectionSummary: "الملخص",
    revenueReportTitle: "تقرير الإيرادات",
    expensesReportTitle: "تقرير المصاريف",
    reportSummaryTitle: "ملخص التقرير",
    columnTenant: "المستأجر",
    columnMonthlyRent: "الإيجار الشهري",
    columnProperty: "العقار",
    columnDescription: "الوصف",
    columnAmount: "المبلغ",
    columnCategory: "الفئة",
    columnDate: "التاريخ",
    columnRent: "الإيجار",
    activeTenants: "المستأجرون النشطون",
    reportFooter: "أملاكي — مدير أملاكك الذكي",
    // Profile
    footerText: "أملاكي - مدير عقاراتك الذكي",
    addYourName: "أضف اسمك",
    langChanged: "تم تغيير اللغة",
    langChangedMsg: "أعد تشغيل التطبيق لتطبيق الاتجاه العربي الكامل.",
    ok: "حسناً",
    infoSaved: "تم حفظ المعلومات",
    database: "قاعدة البيانات",
    connected: "متصل",
    // Personal Info
    emailLabel: "البريد الإلكتروني",
    fullNameLabel: "الاسم الكامل", firstNameLabel: "الاسم الأول", lastNameLabel: "اسم العائلة",
    phoneLabel: "رقم الجوال",
    cityLabel: "المدينة",
    companyLabel: "الشركة / العمل",
    companyPlaceholder: "أملاكي للعقارات",
    cityPlaceholder: "الرياض",
    // Splash
    appName: "أملاكي",
    smartPropertyManager: "مدير املاكك الذكي",
    // Unit detail
    endLease: "إنهاء العقد",
    frequency: "دورية الدفع",
    holdToEdit: "اضغط مطولاً للتعديل",
    editPayment: "تعديل الدفعة",
    enterManually: "إدخال يدوي",
    enterManuallyDesc: "أدخل بيانات المستأجر يدوياً",
    fetchFromEjar: "جلب البيانات تلقائياً من عقد إيجار",
    paymentFrequencyLabel: "دورية الدفع",
    exampleBankTransfer: "مثال: تحويل بنكي",
    // Dashboard / calendar
    leaseEndLabel: "نهاية عقد",
    todayLabel: "اليوم",
    calSun: "ح", calMon: "ن", calTue: "ث", calWed: "أ", calThu: "خ", calFri: "ج", calSat: "س",
    // Calendar events
    calLeaseEnd: "نهاية عقد الإيجار",
    calRentDue: "موعد سداد الإيجار",
    calPaymentRecorded: "دفعة مسجلة",
    // Tenants
    noTenantsShort: "لا يوجد مستأجرون",
    leaseStartRequired: "تاريخ بداية العقد مطلوب",
    leaseEndRequired: "تاريخ انتهاء العقد مطلوب",
    syncing: "مزامنة...",
    // Recent updates
    newTenantAdded: "مستأجر جديد",
    rentCollected: "تم تحصيل الإيجار",
    paymentReceived: "دفعة مستلمة",
    tapToView: "اضغط للعرض",
    // Tenant search
    expiresToday: "ينتهي اليوم",
    expiresInDays: "ينتهي خلال %d% يوم",
    expiringSoon: "ينتهي قريباً",
    deleteTenantMsg: "هل تريد إزالة \"%name%\" من النظام؟ لا يمكن التراجع عن هذا الإجراء.",
    // Ejar import
    loadingInquiryForm: "جاري تحميل نموذج الاستعلام...",
    searching: "جاري البحث...",
    loadingContractDetails: "جاري تحميل تفاصيل العقد...",
    loadingResults: "جاري تحميل النتائج...",
    fillingForm: "جاري تعبئة النموذج...",
    hijriDob: "تاريخ الميلاد الهجري",
    exampleIdNumber: "مثال: 1xxxxxxxxx",
    region: "المنطقة",
    unpaidBills: "غير مدفوعة",
    pickerCancel: "إلغاء",
    pickerDone: "تم",
    pickerDay: "يوم",
    pickerMonth: "شهر",
    pickerYear: "سنة",
    // Expenses recurring
    recurringHintOn: "سيتكرر هذا المصروف تلقائياً كل شهر",
    recurringHintOff: "اضغط لتفعيل التكرار الشهري",
    // Terms & Privacy
    termsOfService: "شروط الاستخدام",
    privacyPolicy: "سياسة الخصوصية",
    bySigningUp: "بتسجيلك، أنت توافق على",
    andWord: "و",
    lastUpdated: "آخر تحديث",
    // Terms sections
    termsIntroTitle: "المقدمة",
    termsIntroBody: "مرحباً بك في أملاكي. تحكم شروط الاستخدام هذه استخدامك لتطبيق إدارة العقارات. باستخدامك لتطبيق أملاكي، فإنك توافق على الالتزام بهذه الشروط. إذا كنت لا توافق، يرجى عدم استخدام التطبيق.",
    termsAccountTitle: "مسؤوليات الحساب",
    termsAccountBody: "أنت مسؤول عن الحفاظ على سرية بيانات حسابك. يجب عليك تقديم معلومات دقيقة وكاملة أثناء التسجيل. توافق على إخطارنا فوراً بأي وصول غير مصرح به إلى حسابك. يجب أن يكون عمرك 18 عاماً على الأقل لإنشاء حساب.",
    termsUsageTitle: "الاستخدام المقبول",
    termsUsageBody: "توافق على استخدام أملاكي فقط لأغراض إدارة العقارات المشروعة. لا يجوز لك إساءة استخدام المنصة لتخزين معلومات مستأجرين مزيفة أو التلاعب بالسجلات المالية أو المشاركة في أي نشاط احتيالي. لا يجوز لك محاولة الهندسة العكسية أو تعديل أو توزيع أي جزء من التطبيق.",
    termsPaymentsTitle: "المدفوعات والبيانات المالية",
    termsPaymentsBody: "يسهّل أملاكي تسجيل وتتبع مدفوعات الإيجار والمصاريف. جميع البيانات المالية المدخلة هي مسؤوليتك للتحقق من دقتها. أملاكي ليس مؤسسة مالية ولا يعالج معاملات مالية فعلية. لسنا مسؤولين عن أي قرارات مالية تُتخذ بناءً على البيانات داخل التطبيق.",
    termsDataTitle: "البيانات والخصوصية",
    termsDataBody: "يخضع استخدامك لأملاكي أيضاً لسياسة الخصوصية الخاصة بنا. باستخدامك للتطبيق، فإنك توافق على جمع واستخدام بياناتك كما هو موضح في سياسة الخصوصية. تحتفظ بملكية جميع بيانات العقارات والمستأجرين التي تدخلها في التطبيق.",
    termsTerminationTitle: "إنهاء الخدمة",
    termsTerminationBody: "نحتفظ بالحق في تعليق أو إنهاء حسابك إذا انتهكت هذه الشروط. يمكنك حذف حسابك في أي وقت من خلال إعدادات التطبيق. عند الإنهاء، قد يتم الاحتفاظ ببياناتك لفترة معقولة لأغراض النسخ الاحتياطي والامتثال القانوني.",
    termsLiabilityTitle: "حدود المسؤولية",
    termsLiabilityBody: "يُقدَّم أملاكي \"كما هو\" دون ضمانات من أي نوع. لن نكون مسؤولين عن أي أضرار غير مباشرة أو عرضية أو تبعية ناتجة عن استخدامك للتطبيق. لن تتجاوز مسؤوليتنا الإجمالية المبلغ الذي دفعته مقابل الخدمة في الأشهر الـ 12 السابقة.",
    termsChangesTitle: "التغييرات على الشروط",
    termsChangesBody: "قد نقوم بتحديث هذه الشروط من وقت لآخر. سنخطرك بالتغييرات المهمة عبر التطبيق أو البريد الإلكتروني. استمرارك في استخدام أملاكي بعد التغييرات يعني قبولك للشروط المحدّثة.",
    termsContactTitle: "تواصل معنا",
    termsContactBody: "إذا كانت لديك أسئلة حول شروط الاستخدام، يرجى التواصل معنا على support@amlakeyapp.com.",
    // Privacy sections
    privacyIntroTitle: "المقدمة",
    privacyIntroBody: "في أملاكي، نأخذ خصوصيتك على محمل الجد. توضح سياسة الخصوصية هذه كيفية جمع واستخدام وتخزين وحماية معلوماتك الشخصية عند استخدامك لتطبيق إدارة العقارات.",
    privacyDataCollectedTitle: "البيانات التي نجمعها",
    privacyDataCollectedBody: "نجمع المعلومات التي تقدمها مباشرة، بما في ذلك: اسمك وبريدك الإلكتروني ورقم هاتفك أثناء التسجيل؛ وتفاصيل العقارات مثل الأسماء والعناوين ومعلومات الوحدات؛ ومعلومات المستأجرين بما في ذلك الأسماء وبيانات الاتصال وشروط العقد؛ والسجلات المالية مثل مدفوعات الإيجار والمصاريف وحسابات الفواتير؛ ومعلومات الجهاز لوظائف التطبيق والأمان.",
    privacyHowWeUseTitle: "كيف نستخدم بياناتك",
    privacyHowWeUseBody: "نستخدم بياناتك من أجل: تقديم وصيانة خدمة إدارة العقارات؛ وإرسال إشعارات حول مواعيد استحقاق الإيجار وانتهاء العقود؛ وإنشاء التقارير وتحليلات الأداء لعقاراتك؛ وتسهيل النسخ الاحتياطي واستعادة البيانات؛ وتحسين تطبيقنا وتجربة المستخدم.",
    privacyDataStorageTitle: "تخزين البيانات والأمان",
    privacyDataStorageBody: "يتم تخزين بياناتك بشكل آمن باستخدام تشفير بمعايير الصناعة. نستخدم Supabase كبنية تحتية للخوادم مع سياسات أمان على مستوى الصفوف. تتوفر المصادقة البيومترية لأمان إضافي للتطبيق. نراجع ونحدّث ممارساتنا الأمنية بانتظام لحماية معلوماتك.",
    privacySharingTitle: "المشاركة مع أطراف ثالثة",
    privacySharingBody: "لا نبيع أو نتاجر أو نؤجر معلوماتك الشخصية لأطراف ثالثة. قد نشارك البيانات فقط مع: مقدمي الخدمات الضروريين لتشغيل التطبيق (الاستضافة، المصادقة)؛ والسلطات القانونية عند الاقتضاء بموجب القانون أو أمر المحكمة؛ وبموافقتك الصريحة لأي غرض آخر.",
    privacyRightsTitle: "حقوقك",
    privacyRightsBody: "لديك الحق في: الوصول إلى جميع بياناتك الشخصية المخزنة في التطبيق وعرضها؛ وتصدير بياناتك في أي وقت من خلال إعدادات التطبيق؛ وطلب تصحيح المعلومات غير الدقيقة؛ وطلب حذف حسابك والبيانات المرتبطة به؛ وسحب الموافقة على معالجة البيانات في أي وقت.",
    privacyChangesTitle: "التغييرات على هذه السياسة",
    privacyChangesBody: "قد نقوم بتحديث سياسة الخصوصية هذه بشكل دوري. سنخطرك بالتغييرات الجوهرية عبر التطبيق. يشير تاريخ \"آخر تحديث\" أعلى هذه الصفحة إلى آخر مرة تم فيها مراجعة السياسة.",
    privacyContactTitle: "تواصل معنا",
    privacyContactBody: "للاستفسارات المتعلقة بالخصوصية، يرجى التواصل معنا على support@amlakeyapp.com.",
    // Subscription
    subscriptionTitle: "الترقية إلى برو",
    currentPlan: "الخطة الحالية",
    freePlan: "مجاني",
    proPlan: "برو",
    proMonthly: "شهري",
    proAnnual: "سنوي",
    proPriceMonth: "/شهر",
    proPriceYear: "/سنة",
    savePercent: "وفر 50%",
    subscribePro: "اشترك في برو",
    restorePurchases: "استعادة المشتريات",
    restoreSuccess: "تم استعادة المشتريات بنجاح!",
    restoreNone: "لم يتم العثور على مشتريات سابقة.",
    subscriptionActive: "اشتراك برو مفعل",
    subscriptionManage: "إدارة الاشتراك",
    upgradeRequired: "الترقية مطلوبة",
    upgradeToUnlock: "قم بالترقية إلى برو لفتح هذه الميزة",
    propertyLimitTitle: "تم الوصول لحد العقارات",
    propertyLimitMsg: "الخطة المجانية تسمح بـ 3 عقارات كحد أقصى. قم بالترقية إلى برو لعقارات غير محدودة.",
    unitLimitTitle: "تم الوصول لحد الوحدات",
    unitLimitMsg: "الخطة المجانية تسمح بـ 5 وحدات لكل عقار. قم بالترقية إلى برو لوحدات غير محدودة.",
    upgrade: "ترقية",
    later: "لاحقاً",
    proFeatures: "مميزات برو",
    featureUnlimitedProperties: "عقارات غير محدودة",
    featureUnlimitedUnits: "وحدات غير محدودة",
    featureWhatsAppBroadcast: "رسائل واتساب جماعية",
    featureExportReports: "تصدير التقارير",
    featureDarkMode: "الوضع الداكن",
    featureUnlimitedPropertiesDesc: "أضف عقارات غير محدودة لإدارة محفظتك",
    featureUnlimitedUnitsDesc: "بدون حد على عدد الوحدات لكل عقار",
    featureWhatsAppBroadcastDesc: "أرسل رسائل جماعية للمستأجرين عبر واتساب",
    featureExportReportsDesc: "صدّر وشارك تقارير الأداء",
    featureDarkModeDesc: "مريح للعين مع الوضع الداكن",
    featureVault: "خزنة المستندات",
    featureVaultDesc: "احفظ صكوك الملكية والعقود والمستندات المهمة بأمان",
    vault: "الخزنة",
    vaultTitle: "خزنة المستندات",
    addDocument: "رفع مستند",
    documentName: "اسم المستند",
    documentType: "نوع المستند",
    selectProperty: "اختر العقار",
    expiryDate: "تاريخ الانتهاء",
    noDocuments: "لا توجد مستندات بعد",
    noDocumentsDesc: "اضغط + لرفع أول مستند.",
    uploadSuccess: "تم رفع المستند بنجاح",
    deleteDocument: "حذف المستند",
    deleteDocumentConfirm: "هل أنت متأكد من حذف هذا المستند؟",
    viewDocument: "عرض المستند",
    downloadDocument: "تحميل",
    documents: "المستندات",
    docTypeDeed: "صك الملكية",
    docTypePermit: "رخصة البناء",
    docTypeContract: "عقد الإيجار",
    docTypeInsurance: "وثيقة التأمين",
    docTypeMaintenance: "سجل الصيانة",
    docTypeTax: "مستند ضريبي",
    docTypeOther: "أخرى",
    allDocuments: "الكل",
    documentExpiring: "ينتهي قريباً",
    documentExpired: "منتهي",
    uploading: "جاري الرفع...",
    freeIncludes: "الخطة المجانية تشمل",
    freeProperties: "حتى 3 عقارات",
    freeUnits: "حتى 5 وحدات لكل عقار",
    freePaymentTracking: "تتبع المدفوعات",
    freeNotifications: "الإشعارات",
    freeEjarImport: "استيراد إيجار",
    cancelAnytime: "إلغاء في أي وقت. الاشتراكات تتجدد تلقائياً.",
    // Landing page
    landingLogin: "تسجيل الدخول",
    landingGetStarted: "ابدأ الآن",
    landingDownload: "حمّل من App Store",
    landingUseWeb: "استخدم عبر الويب",
    landingHeroTag: "إدارة العقارات أصبحت أسهل",
    landingHeroTitle1: "أدر عقاراتك",
    landingHeroTitle2: "باحترافية",
    landingHeroDesc: "المنصة المتكاملة المصممة للمُلّاك السعوديين. تابع العقارات والمستأجرين والمدفوعات والمصاريف من جوالك أو المتصفح.",
    landingTrustedBy: "موثوق من قبل مُلّاك عقارات في جميع أنحاء المملكة",
    landingFeaturesTitle: "كل ما تحتاجه لإدارة عقاراتك",
    landingFeaturesSub: "مصمم للمُلّاك السعوديين الذين يريدون البساطة والتحكم",
    landingFeat1Title: "محفظة العقارات",
    landingFeat1Desc: "أدر الشقق والفلل والمباني التجارية والأراضي في مكان واحد.",
    landingFeat2Title: "إدارة المستأجرين",
    landingFeat2Desc: "تتبع بيانات المستأجرين وتواريخ العقود ومعلومات التواصل بسهولة.",
    landingFeat3Title: "تتبع المدفوعات",
    landingFeat3Desc: "سجّل دفعات الإيجار وتتبع المبالغ المتأخرة ولا تفوّت أي تحصيل.",
    landingFeat4Title: "تقارير الأداء",
    landingFeat4Desc: "شاهد معدلات التحصيل وتفاصيل الإيرادات والأداء المالي بنظرة واحدة.",
    landingFeat5Title: "إشعارات واتساب",
    landingFeat5Desc: "أرسل تذكيرات الدفع ورسائل تجديد العقود للمستأجرين مباشرة عبر واتساب.",
    landingFeat6Title: "تنبيهات ذكية",
    landingFeat6Desc: "احصل على إشعارات فورية للمدفوعات المتأخرة والعقود المنتهية والتذكيرات المهمة.",
    landingFeat7Title: "تتبع المصاريف",
    landingFeat7Desc: "سجّل تكاليف الصيانة وفواتير الخدمات وجميع مصاريف العقار في مكان واحد.",
    landingFeat8Title: "لوحة تحكم تحليلية",
    landingFeat8Desc: "نظرة شاملة على الإيرادات ومعدلات التحصيل وصافي الدخل ونسبة الإشغال.",
    landingFeat9Title: "دعم ثنائي اللغة",
    landingFeat9Desc: "واجهة كاملة بالعربية والإنجليزية مع دعم كامل للاتجاه. بدّل في أي وقت.",
    landingFeat10Title: "الوضع الداكن",
    landingFeat10Desc: "مريح للعين. بدّل بين الوضع الفاتح والداكن بضغطة واحدة.",
    landingFeat11Title: "متعدد المنصات",
    landingFeat11Desc: "يعمل على الآيفون والمتصفح. بياناتك متزامنة في كل مكان.",
    landingFeat12Title: "تصدير التقارير",
    landingFeat12Desc: "إنشاء تقارير PDF و Excel للمدفوعات والمصاريف وأداء العقارات.",
    landingStatsProperties: "عقار مُدار",
    landingStatsTransactions: "معاملة مُسجلة",
    landingStatsUptime: "وقت التشغيل",
    landingStatsPlatforms: "منصات",
    landingHowTitle: "كيف يعمل",
    landingHowSub: "ابدأ في دقائق، وليس ساعات",
    landingHow1Title: "أنشئ حسابك",
    landingHow1Desc: "سجّل مجاناً في ثوانٍ باستخدام بريدك الإلكتروني فقط.",
    landingHow2Title: "أضف عقاراتك",
    landingHow2Desc: "أدخل عقاراتك ووحداتك. استورد من إيجار إن أردت.",
    landingHow3Title: "أدر كل شيء",
    landingHow3Desc: "تابع المستأجرين، حصّل الإيجارات، راقب المصاريف، ونمّ محفظتك.",
    landingCtaTitle: "مستعد لتبسيط إدارة عقاراتك؟",
    landingCtaSub: "انضم للمُلّاك في جميع أنحاء المملكة الذين يثقون بأملاكي.",
    landingPricingTitle: "سعر بسيط بإمكانيات ضخمة",
    landingPricingSub: "ابدأ مجاناً، وقم بالترقية عند الحاجة",
    landingFree: "مجاني",
    landingPro: "برو",
    landingBestValue: "الأفضل قيمة",
    landingOrYearly: "أو 89 ر.س/سنة (وفر 50%)",
    landingPriceFreeItems: "حتى 3 عقارات|5 وحدات لكل عقار|تتبع المدفوعات|الإشعارات|رسائل واتساب|الوضع الداكن",
    landingPriceFreeDisabled: "تصدير التقارير|خزنة المستندات",
    landingPriceProItems: "عقارات غير محدودة|وحدات غير محدودة|تتبع المدفوعات|الإشعارات|رسائل واتساب|تصدير التقارير (PDF و Excel)|خزنة المستندات",
    landingBilingualTitle: "ثنائي اللغة بالكامل",
    landingBilingualSub: "تبديل بين الإنجليزية والعربية مع دعم كامل للاتجاه من اليمين لليسار",
    landingFooterBrand: "Amlakey | أملاكي",
    landingFooterSub: "مدير عقاراتك الذكي",
    landingFooterContact: "تواصل معنا",
    landingCopyright: "© 2026 أملاكي. جميع الحقوق محفوظة.",
  },
};

export type TKey = keyof typeof translations.en;

interface LangCtx {
  lang: Language; toggle: () => void; setLanguage: (l: Language) => void; t: (k: TKey) => string; isRTL: boolean;
}

const LanguageContext = createContext<LangCtx>({
  lang: "ar", toggle: () => {}, setLanguage: () => {}, t: (k) => k, isRTL: true,
});

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLang] = useState<Language>("ar");
  const [initialized, setInitialized] = useState(false);

  useEffect(() => {
    AsyncStorage.getItem("@lang").then((v) => {
      if (v === "en" || v === "ar") {
        setLang(v);
      } else {
        // First launch — detect device locale, default to Arabic
        try {
          const locales = getLocales();
          const deviceLang = locales?.[0]?.languageCode;
          const detected: Language = deviceLang === "en" ? "en" : "ar";
          setLang(detected);
          AsyncStorage.setItem("@lang", detected).catch(() => {});
        } catch {
          // Fallback to Arabic (default)
          AsyncStorage.setItem("@lang", "ar").catch(() => {});
        }
      }
    }).catch(() => {}).finally(() => setInitialized(true));
  }, []);

  // Sync document direction on web whenever language changes
  useEffect(() => {
    if (Platform.OS === "web" && typeof document !== "undefined") {
      document.documentElement.dir = lang === "ar" ? "rtl" : "ltr";
      document.documentElement.lang = lang;
    }
  }, [lang]);

  const applyLanguage = async (next: Language) => {
    const needsRTLChange = Platform.OS !== "web" && I18nManager.isRTL !== (next === "ar");
    setLang(next);
    await AsyncStorage.setItem("@lang", next);
    if (needsRTLChange) {
      I18nManager.allowRTL(next === "ar");
      I18nManager.forceRTL(next === "ar");
      // I18nManager changes require a reload to take effect
      if (Updates.isEnabled) {
        try {
          await Updates.reloadAsync();
        } catch {
          // reloadAsync failed — fall through to alert
        }
      }
      // If updates disabled or reload failed, ask user to restart
      if (!Updates.isEnabled) {
        const { Alert } = require("react-native");
        Alert.alert(
          next === "ar" ? "أعد تشغيل التطبيق" : "Restart Required",
          next === "ar"
            ? "يرجى إغلاق التطبيق وإعادة فتحه لتطبيق تغيير اللغة."
            : "Please close and reopen the app to apply the language change.",
        );
      }
    }
  };

  const toggle = () => applyLanguage(lang === "en" ? "ar" : "en");
  const setLanguage = (l: Language) => applyLanguage(l);

  const t = (k: TKey): string => (translations[lang][k] as string) ?? k;

  // Block children until async language initialization completes to prevent
  // context access crashes on native with Hermes + React Compiler
  if (!initialized) return null;

  return (
    <LanguageContext.Provider value={{ lang, toggle, setLanguage, t, isRTL: lang === "ar" }}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLanguage = () => useContext(LanguageContext);
